name: HotPotato
version: '${project.version}'
main: me.bubbles.hotpotato.HotPotato
api-version: 1.19
commands:
  hotpotato:
    usage: </command>
    description: Base hot potato command
    aliases: [hp]
